---
- name: Install docker
  hosts: all
  become: yes
  tasks:
    - name: add docker apt key
      apt_key: >
        id=58118E89F3A912897C070ADBF76221572C52609D
        keyserver=hkp://p80.pool.sks-keyservers.net:80
        state=present

    - name: add docker apt repository
      apt_repository: >
        repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main"
        state=present
        update_cache=yes

    - name: install docker and requirements
      apt: >
        pkg={{item}}
        state=present
      with_items:
        - apparmor
        - docker-engine

    - name: configure docker
      copy: content='DOCKER_OPTS=""'
        dest=/etc/default/docker
      notify: restart docker

    - name: allow vagrant user to run docker commands without sudo
      user: name=vagrant append=yes groups=docker

    - name: install required python packages for ansible and docker
      apt: pkg={{item}} state=latest
      with_items: [python-pip, python-dev]
    
    - name: Install Docker Python library.
      pip: name=docker-py state=present
      become: yes

  handlers:
    - name: restart docker
      command: service docker restart
